version: '3'
services:
##### STUDIO DASHBOARD
  studio-dashboard:
    build: 
      context: ./studio-dashboard/dashboard
      args:
        COMMIT: 70033f5
        REPOSITORY: https://github.com/Radio-Eastern-FM/Studio-Dashboard.git
    ports:
      - 3000:80
  event-source:
    build: 
      context: ./studio-dashboard/event-source
      args:
        COMMIT: d78a126
        REPOSITORY: https://github.com/Radio-Eastern-FM/Event-Source-Service.git
    container_name: event-source
    depends_on:
      - mqtt
    environment:
      - PYTHONUNBUFFERED=1
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./studio-dashboard/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./studio-dashboard/mqtt/EFM_passwords.conf:/mosquitto/config/EFM_passwords.conf
##### OB-SERVER
  ob-server:
    build:
      context: ./observer
      args:
        OBCONF_PASS: ${OBCONF_PASS}
        OBCONF_EMAIL: ${OBCONF_EMAIL}
        MYSQL_PASS: ${MYSQL_PASS}
        OB_UPDATES_PW: ${OB_UPDATES_PW}
        OBCONF_URL: ${OBCONF_URL}
        OBCONF_SALT: ${OBCONF_SALT}
        COMMIT: 1869edd
        REPOSITORY: https://github.com/openbroadcaster/observer.git
        MODULE_NAMES: "bulk_import ob2ob data_and_statistics rds"
        MODULE_REPOSITORIES: "('https://github.com/openbroadcaster/bulk-import' 'https://github.com/openbroadcaster/ob2ob' 'https://github.com/openbroadcaster/statistics' 'https://github.com/openbroadcaster/rds')"
    volumes:
      - ./observer/nginx/observer.conf:/etc/nginx/sites-available/observer.conf
      - ./observer/startup.sh:/home/startup.sh
      - ./observer/www:/var/www/html
    ports:
      - "8080:80"
  ob-player:
    depends_on:
      - ob-server
    build:
      context: ./obplayer
      args:
        REPOSITORY: https://github.com/openbroadcaster/obplayer.git
        COMMIT: c971548
    ports:
      - "8081:80"
  belt:
    build: 
      context: ./belt
      args:
        COMMIT: c7d7f06
        REPOSITORY: https://github.com/Radio-Eastern-FM/Belt.git
    depends_on:
      - ob-server
      - ob-player
      - studio-dashboard
    ports:
      - 3001:80
  telemetry:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./telemetry/config.yaml:/etc/otel/config.yaml
