version: '3'
services:
##### STUDIO DASHBOARD
  studio-dashboard:
    build: 
      context: ./studio-dashboard/dashboard
      args:
        COMMIT: d48fabd
        REPOSITORY: https://github.com/Radio-Eastern-FM/Studio-Dashboard.git
    restart: always
    depends_on:
      - mqtt
      - event-source
    container_name: studio-dashboard
    ports:
      - 3000:80
  event-source:
    build: 
      context: ./studio-dashboard/event-source
      args:
        COMMIT: 9240ebb
        REPOSITORY: https://github.com/Radio-Eastern-FM/Event-Source-Service.git
    restart: always
    container_name: event-source
    depends_on:
      - mqtt
    environment:
      - PYTHONUNBUFFERED=1
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
  mqtt:
    image: eclipse-mosquitto
    restart: always
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./studio-dashboard/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./studio-dashboard/mqtt/EFM_passwords.conf:/mosquitto/config/EFM_passwords.conf
##### OB-SERVER
  ob-server:
    restart: always
    container_name: ob-server
    depends_on:
      - mysql-db
    build:
      context: ./observer
      args:
        OBCONF_PASS: ${OBCONF_PASS}
        OBCONF_EMAIL: ${OBCONF_EMAIL}
        OB_DB_USER: ${MYSQL_USER}
        OB_DB_PASS: ${MYSQL_PASS}
        OB_DB_HOST: mysql-db:3306
        OB_DB_NAME: ${DBNAME}
        OB_UPDATES_PW: ${OB_UPDATES_PW}
        OBCONF_URL: ${OBCONF_URL}
        OBCONF_SALT: ${OBCONF_SALT}
        COMMIT: 1869edd
        MODULE_NAMES: "bulk_import ob2ob data_and_statistics rds"
        MODULE_REPOSITORIES: "('https://github.com/openbroadcaster/bulk-import' 'https://github.com/openbroadcaster/ob2ob' 'https://github.com/openbroadcaster/statistics' 'https://github.com/openbroadcaster/rds')"
    volumes:
      - ./observer/nginx/observer.conf:/etc/nginx/sites-available/observer.conf
      - ./observer/startup.sh:/home/startup.sh
      - ./observer/www:/var/www/html
      - ob-server-home:/home
    environment:
      OBCONF_PASS: ${OBCONF_PASS}
    ports:
      - "8080:80"
  ob-player:
    build:
      context: ./obplayer
      args:
        COMMIT: c971548
    container_name: ob-player
    # restart: always
    depends_on:
      - ob-server
    ports:
      - "8081:23233"
##### BELT
  belt:
    build: 
      context: ./belt
      args:
        COMMIT: c4b3943
    restart: always
    container_name: belt
    depends_on:
      - ob-server
      - ob-player
      - studio-dashboard
    ports:
      - 3001:80
    volumes:
      - ./belt/nginx/belt.conf:/etc/nginx/conf.d/default.conf
##### OBSERVABILITY
  telemetry:
    container_name: telemetry
    image: otel/opentelemetry-collector-contrib
    restart: always
    volumes:
      - ./telemetry/config.yaml:/etc/otel/config.yaml
###### API
  api:
    build:
      context: ./api/apollo
      args:
        COMMIT: 6ffc3b9
    depends_on:
      - mongo-db
    container_name: api
    ports:
      - 4000:4000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-db-data:/data/db
      - mongo-db-config:/data/configdb
      - ./api/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: MYDB
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mysql-db
    ports:
      - 8001:8080
  mysql-db:
    cap_add:
      - SYS_NICE
    build:
      context: ./observer/mysql
      args:
        COMMIT: 1869edd
    container_name: mysql-db
    restart: always
    volumes:
      - mysql-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_TCP_PORT: 3306
volumes:
  mongo-db-data:
  mongo-db-config:
  mysql-db-data:
  ob-server-home:
